# Generated by Django 2.1.3 on 2018-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_data_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_id',
            field=models.TextField(null=True),
        ),
    ]
