# Generated by Django 2.1.3 on 2018-12-12 11:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_project_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
