# Generated by Django 2.1.3 on 2018-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_auto_20181214_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='external_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='external_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='external_id',
            field=models.TextField(unique=True),
        ),
    ]
