# Generated by Django 2.1.3 on 2018-12-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20181217_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Workspace'),
        ),
    ]
